import {initialCatalog,migrateCatalog,effectiveProject} from './catalog.js?v=multi1';
import {analyse,calculate,money} from './core.js?v=multi1';
import {optionKey,migrateSelections,selectedOptions,combinedTotal,proposal} from './quote.js?v=multi1';
const $=id=>document.getElementById(id), esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const defaults={projects:initialCatalog,d:{client:'',company:'',email:'',phone:'',date:'',place:'',participants:'',budget:'',context:'',duration:'',km:''},r:{seats:3,kmRate:0.6,tolls:0,meal:0,deposit:30},project:'0',request:'',tax:''};
let state;try{state=JSON.parse(localStorage.getItem('mc-quotes-v1'))||structuredClone(defaults)}catch{state=structuredClone(defaults)}
state.projects=migrateCatalog(state.projects);
state.r.hotel??='';
migrateSelections(state);
let routeVersion=0;
function save(){try{localStorage.setItem('mc-quotes-v1',JSON.stringify(state));return true}catch{$('copy-status').textContent='Sauvegarde locale indisponible : exportez vos données.';return false}}
const field=(id,label,value,type='text')=>`<label>${esc(label)}<input data-field="${id}" type="${type}" ${type==='number'?'min="0" step="any"':''} value="${esc(value)}"></label>`;
const dLabels={client:'Nom du contact',company:'Société / client',email:'E-mail',phone:'Téléphone',date:'Date(s) envisagée(s)',place:'Lieu / adresse',participants:'Nombre de participants',budget:'Budget annoncé (€) — base HT/TTC à confirmer',context:'Contexte de l’événement',duration:'Durée / horaires demandés'};
function renderFields(){ $('fields').innerHTML=Object.entries(dLabels).map(([k,v])=>field(k,v,state.d[k],['participants','budget'].includes(k)?'number':'text')).join('');$('fields').querySelectorAll('input').forEach(el=>el.oninput=()=>{state.d[el.dataset.field]=el.value;if(el.dataset.field==='place'){state.d.km='';$('km').value='';routeVersion++;$('geo-results').replaceChildren();$('route-status').textContent='Lieu modifié : recalculer la distance.'}update()});$('km').value=state.d.km; }
function renderChoices(){
 $('project-choices').innerHTML=state.projects.map(p=>`<fieldset class="project-choice"><legend>${esc(p.name)} <small>${esc(p.category)}</small></legend>${(p.formulas||[null]).map(f=>{const key=optionKey(p.id,f?.id||''),v=f||p;return `<label class="check-option"><input type="checkbox" data-option="${esc(key)}" ${state.selections.includes(key)?'checked':''}><span>${esc(f?.name||p.name)}<small>${v.artists||'Effectif à définir'} artistes · ${v.base===''?'Tarif à définir':money(Number(v.base))+' HT'}${f?' hors VHR':''}</small></span></label>`}).join('')}</fieldset>`).join('');
 $('project-choices').querySelectorAll('[data-option]').forEach(el=>el.onchange=()=>{state.selections=el.checked?[...new Set([...state.selections,el.dataset.option])]:state.selections.filter(k=>k!==el.dataset.option);update()});
 $('quote-mode').value=state.mode;
}
function update(){
 const options=selectedOptions(state),d=state.d,fmt=v=>v===null?'À compléter':money(v);
 $('selection-count').textContent=options.length+' sélection(s)';
 $('maps').href='https://www.google.com/maps/dir/?api=1&origin=Gretz-Armainvilliers+77220+France&destination='+encodeURIComponent(d.place||'France')+'&travelmode=driving';
 $('costs').innerHTML=options.map(o=>`<section class="option-cost"><h3>${esc(o.label)}</h3>${[['Artistes / véhicules',o.c.artists+' / '+o.c.cars],['Prestation artistique HT',fmt(o.c.fee)],['Voyage et restauration',fmt(o.c.travel)],...(o.p.formulaName?[['Hébergement HT',o.hotel===''?'À compléter':money(Number(o.hotel))]]:[]),['Total HT',fmt(o.c.total)],['Acompte ('+state.r.deposit+' %)',fmt(o.c.deposit)]].map(([k,v])=>`<div class="cost-row"><span>${esc(k)}</span><span>${esc(v)}</span></div>`).join('')}${o.p.formulaName?`<label>Hébergement total HT pour ${esc(o.label)} (€)<input type="number" min="0" step="0.01" data-hotel="${esc(o.key)}" value="${esc(o.hotel)}" placeholder="0 si inutile ou pris en charge"></label>`:''}</section>`).join('');
 if(state.mode==='cumulative'&&options.length)$('costs').insertAdjacentHTML('beforeend',`<div class="cost-row total"><span>Total général HT</span><span>${fmt(combinedTotal(options))}</span></div><p class="hint">Chaque équipe conserve ses véhicules et frais propres. Aucune mutualisation automatique.</p>`);
 $('costs').querySelectorAll('[data-hotel]').forEach(el=>el.onchange=()=>{if(el.checkValidity()){state.hotels[el.dataset.hotel]=el.value;update()}});
 const warnings=[];if(!options.length)warnings.push('Cochez au moins un projet ou une formule.');
 for(const o of options){if(o.c.total===null)warnings.push(o.label+' : chiffrage incomplet.');if(!o.c.artists)warnings.push(o.label+' : effectif à préciser.');if(o.p.capacity&&Number(d.participants)>Number(o.p.capacity))warnings.push(o.label+' : capacité dépassée.');if(state.mode!=='cumulative'&&d.budget&&o.c.total!==null&&o.c.total>Number(d.budget))warnings.push(o.label+' : dépasse le budget annoncé.');}
 if(state.mode==='cumulative'&&d.budget&&combinedTotal(options)!==null&&combinedTotal(options)>Number(d.budget))warnings.push('Le total général dépasse le budget annoncé.');
 for(const k of ['date','place','participants'])if(!d[k])warnings.push(dLabels[k]+' à préciser.');
 if(/\bou\b|environs/i.test(d.date+' '+d.place))warnings.push('Date ou lieu alternatif à confirmer.');
 $('warnings').textContent=warnings.join(' ');
 $('subject').value='Proposition Music Concept'+(d.company?' — '+d.company:'')+(d.date?' — '+d.date:'');
 $('email-preview').value=proposal(state,options);save();
}
function renderCatalog(){
 const pricing={base:'Forfait artistique HT hors VHR (€)',perArtist:'Supplément par artiste (€)',perPerson:'Supplément par participant (€)',artists:'Effectif total (sosie inclus)',ratio:'Participants par intervenant (optionnel)',capacity:'Capacité maximale (optionnelle)',minCars:'Véhicules minimum',duration:'Durée du spectacle',includes:'Composition / éléments inclus'};
 const common={keywords:'Mots-clés séparés par des virgules',description:'Présentation commerciale',videos:'Liens vidéo'};
 const inputs=(prefix,obj,labels)=>Object.entries(labels).map(([k,label])=>field(prefix+'|'+k,label,obj[k]??'', ['base','perArtist','perPerson','artists','ratio','capacity','minCars'].includes(k)?'number':'text')).join('');
 $('catalog-list').innerHTML=state.projects.map(p=>`<details><summary>${esc(p.name)}<small>${esc(p.category)} · ${p.formulas?p.formulas.length+' formule(s)':p.base===''?'Tarif à définir':money(Number(p.base))}</small></summary><p><a href="${esc(p.source)}" target="_blank" rel="noopener">Informations du site ↗</a></p><div class="grid">${inputs(p.id,p,common)}</div>${p.formulas?field(p.id+'|conditions','Conditions techniques et VHR',p.conditions)+p.formulas.map(f=>`<fieldset><legend>${esc(f.name)}</legend><div class="grid">${inputs(p.id+'|'+f.id,f,pricing)}</div></fieldset>`).join(''):`<div class="grid">${inputs(p.id,p,pricing)}</div>`}<p class="hint">Véhicules = effectif / places, arrondi au supérieur, avec le minimum configuré. Le matériel peut nécessiter des véhicules supplémentaires. Les tarifs fournis excluent voyage, hébergement et restauration.</p></details>`).join('');
 $('catalog-list').querySelectorAll('input').forEach(el=>el.oninput=()=>{if(!el.checkValidity())return;const parts=el.dataset.field.split('|'),p=state.projects.find(p=>p.id===parts[0]);const target=parts.length===3?p.formulas.find(f=>f.id===parts[1]):p;target[parts.at(-1)]=el.value;renderChoices();update()});
}
function renderSettings(){const labels={seats:'Artistes par voiture (conducteur inclus)',kmRate:'Coût par km et par véhicule (€)',tolls:'Péages aller-retour par véhicule (€)',meal:'Repas par artiste (€)',deposit:'Acompte (%)'};$('settings-fields').innerHTML=Object.entries(labels).map(([k,v])=>field(k,v,state.r[k],'number')).join('');$('settings-fields').querySelectorAll('input').forEach(el=>{if(el.dataset.field==='deposit')el.max=100;if(el.dataset.field==='seats')el.min=1;el.oninput=()=>{if(!el.checkValidity()||el.value==='')return;state.r[el.dataset.field]=Number(el.value);update()}});$('tax').value=state.tax;}
function init(){$('request').value=state.request;renderChoices();renderFields();renderCatalog();renderSettings();update()}
document.querySelectorAll('[data-tab]').forEach(b=>b.onclick=()=>{document.querySelectorAll('[data-tab]').forEach(x=>x.classList.toggle('active',x===b));['quote','catalog','settings'].forEach(id=>$(id).hidden=id!==b.dataset.tab)});
$('request').oninput=()=>{state.request=$('request').value;save()};
$('analyze').onclick=()=>{if(!$('request').value.trim())return;const result=analyse($('request').value,state.projects);const{ranked,...d}=result;state.d={...d,km:''};routeVersion++;$('geo-results').replaceChildren();$('route-status').textContent='Distance à calculer pour cette demande.';$('match-note').textContent=ranked.length?'Suggestions par mots-clés : '+ranked.slice(0,3).map(r=>state.projects.find(p=>p.id===r.id).name).join(' · '):'Aucune correspondance détectée. Choisissez une animation.';$('analysis-note').textContent='Extraction effectuée. Vérifiez les champs, notamment le contact, les dates et le lieu. Les champs vides n’ont pas été identifiés.';renderFields();update()};
$('example').onclick=()=>{state.request='Bonjour,\nContact : Naëlla\nÉvénement : séminaire d’entreprise / Team Building\nNous aimerions une animation Samba Experience pour 50 participants le 1er ou le 8 octobre 2026.\nLieu : Colombes ou ses environs\nBudget : 1000 €\nDurée : 1h15 à 1h30, horaires à définir.\nMerci pour votre proposition.';$('request').value=state.request;save()};
$('quote-mode').onchange=()=>{state.mode=$('quote-mode').value;update()};
$('km').oninput=()=>{if($('km').checkValidity()){state.d.km=$('km').value;routeVersion++;$('route-status').textContent='Distance saisie manuellement.';update()}};$('tax').oninput=()=>{state.tax=$('tax').value;update()};
async function fetchJSON(url){const res=await fetch(url,{signal:AbortSignal.timeout(15000)});if(!res.ok)throw Error('Service indisponible');return res.json()}
$('route').onclick=async()=>{if(!state.d.place){$('route-status').textContent='Renseignez d’abord le lieu.';return}const version=++routeVersion;$('route').disabled=true;$('route-status').textContent='Recherche du lieu…';$('geo-results').replaceChildren();try{const results=await fetchJSON('https://nominatim.openstreetmap.org/search?format=json&countrycodes=fr&limit=5&q='+encodeURIComponent(state.d.place.replace(/\s+ou\s+ses\s+environs.*/i,'')));if(version!==routeVersion)return;$('route-status').textContent=results.length?'Sélectionnez le lieu exact. Seule l’adresse est transmise aux services OpenStreetMap / OSRM.':'Lieu introuvable : précisez l’adresse ou saisissez la distance.';for(const result of results){const b=document.createElement('button');b.textContent=result.display_name;b.onclick=async()=>{const selectedVersion=++routeVersion;$('route-status').textContent='Calcul de la distance routière…';try{const origins=await fetchJSON('https://nominatim.openstreetmap.org/search?format=json&limit=1&q=Gretz-Armainvilliers%2077220%20France');if(!origins.length)throw Error();const o=origins[0];const route=await fetchJSON(`https://router.project-osrm.org/route/v1/driving/${o.lon},${o.lat};${result.lon},${result.lat}?overview=false`);if(selectedVersion!==routeVersion)return;if(!route.routes?.length)throw Error();state.d.km=String(Math.round(route.routes[0].distance/100)/10);$('km').value=state.d.km;$('route-status').textContent='Itinéraire routier estimé (OSRM) vers '+result.display_name+'. Vérifiez l’adresse finale, les péages et les accès.';$('geo-results').replaceChildren();update()}catch{if(selectedVersion===routeVersion)$('route-status').textContent='Calcul indisponible. Vérifiez sur Google Maps et saisissez les kilomètres aller.'}};$('geo-results').append(b)}}catch{if(version===routeVersion)$('route-status').textContent='Service indisponible. Utilisez Google Maps puis saisissez la distance aller.'}finally{$('route').disabled=false}};
const fullMail=()=>`Objet : ${$('subject').value}\n\n${$('email-preview').value}`;
$('copy').onclick=async()=>{try{await navigator.clipboard.writeText(fullMail());$('copy-status').textContent='Mail copié.'}catch{$('email-preview').select();$('copy-status').textContent='Sélectionnez le texte puis copiez-le avec Ctrl/Cmd+C.'}};
function download(name,text,type){const url=URL.createObjectURL(new Blob([text],{type}));const a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}
$('download').onclick=()=>download('proposition-music-concept.txt',fullMail(),'text/plain;charset=utf-8');$('backup').onclick=()=>download('music-concept-sauvegarde.json',JSON.stringify(state,null,2),'application/json');
$('restore').onchange=async e=>{try{const s=JSON.parse(await e.target.files[0].text());if(!Array.isArray(s.projects)||s.projects.length!==13||!s.d||!s.r||typeof s.request!=='string'||typeof s.tax!=='string')throw Error();for(const key of Object.keys(defaults.d))if(typeof s.d[key]!=='string')throw Error();for(const key of Object.keys(defaults.r))if(!Number.isFinite(Number(s.r[key]))||Number(s.r[key])<0)throw Error();if(s.r.seats<1||s.r.deposit>100)throw Error();s.projects.forEach((p,i)=>{if(p.id!==String(i))throw Error();for(const k of Object.keys(initialCatalog[i]))if(typeof p[k]!=='string'&&typeof p[k]!=='number')throw Error();for(const k of ['base','perArtist','perPerson','artists','ratio','capacity','minCars'])if(!Number.isFinite(Number(p[k]))||Number(p[k])<0)throw Error();p.source=initialCatalog[i].source});for(const p of s.projects){if(p.formulas){if(!Array.isArray(p.formulas)||!p.formulas.length||typeof p.conditions!=='string')throw Error();for(const f of p.formulas){if(typeof f.id!=='string'||typeof f.name!=='string'||typeof f.duration!=='string'||typeof f.includes!=='string')throw Error();for(const k of ['base','artists','perArtist','perPerson','ratio','capacity','minCars'])if(f[k]===undefined||!Number.isFinite(Number(f[k]))||Number(f[k])<0)throw Error();}}}if(s.r.hotel!==undefined&&s.r.hotel!==''&&(!Number.isFinite(Number(s.r.hotel))||Number(s.r.hotel)<0))throw Error();s.projects=migrateCatalog(s.projects);s.r.hotel??='';if(s.selections!==undefined&&(!Array.isArray(s.selections)||s.selections.some(k=>typeof k!=='string')))throw Error();if(s.hotels!==undefined&&(!s.hotels||Array.isArray(s.hotels)||typeof s.hotels!=='object'||Object.values(s.hotels).some(v=>v!==''&&(!Number.isFinite(Number(v))||Number(v)<0))))throw Error();state=migrateSelections(s);routeVersion++;init();$('restore-status').textContent='Sauvegarde importée.'}catch{$('restore-status').textContent='Fichier invalide : aucune donnée importée.'}};
$('print').onclick=()=>{const pre=document.createElement('div');pre.className='print-mail';pre.textContent=fullMail();document.querySelector('.preview').append(pre);window.print();pre.remove()};init();

window.addEventListener('mc-before-update',e=>{document.querySelectorAll('[data-hotel]').forEach(el=>{if(el.checkValidity())state.hotels[el.dataset.hotel]=el.value;});if(!save())e.preventDefault();});
