import {initialCatalog} from './catalog.js';
import {analyse,calculate,money} from './core.js';
const $=id=>document.getElementById(id), esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const defaults={projects:initialCatalog,d:{client:'',company:'',email:'',phone:'',date:'',place:'',participants:'',budget:'',context:'',duration:'',km:''},r:{seats:3,kmRate:0.6,tolls:0,meal:0,deposit:30},project:'0',request:'',tax:''};
let state;try{state=JSON.parse(localStorage.getItem('mc-quotes-v1'))||structuredClone(defaults)}catch{state=structuredClone(defaults)}
let routeVersion=0;
function save(){try{localStorage.setItem('mc-quotes-v1',JSON.stringify(state))}catch{$('copy-status').textContent='Sauvegarde locale indisponible : exportez vos données.'}}
const field=(id,label,value,type='text')=>`<label>${esc(label)}<input data-field="${id}" type="${type}" ${type==='number'?'min="0" step="any"':''} value="${esc(value)}"></label>`;
const dLabels={client:'Nom du contact',company:'Société / client',email:'E-mail',phone:'Téléphone',date:'Date(s) envisagée(s)',place:'Lieu / adresse',participants:'Nombre de participants',budget:'Budget annoncé (€) — base HT/TTC à confirmer',context:'Contexte de l’événement',duration:'Durée / horaires demandés'};
function renderFields(){ $('fields').innerHTML=Object.entries(dLabels).map(([k,v])=>field(k,v,state.d[k],['participants','budget'].includes(k)?'number':'text')).join('');$('fields').querySelectorAll('input').forEach(el=>el.oninput=()=>{state.d[el.dataset.field]=el.value;if(el.dataset.field==='place'){state.d.km='';$('km').value='';routeVersion++;$('geo-results').replaceChildren();$('route-status').textContent='Lieu modifié : recalculer la distance.'}update()});$('km').value=state.d.km; }
function update(){
 const p=state.projects.find(p=>p.id===state.project)||state.projects[0];state.project=p.id;
 const c=calculate(p,state.d,state.r),d=state.d;
 $('description').innerHTML=`<strong>${esc(p.name)}</strong><br>${esc(p.description)}<br><a href="${esc(p.source)}" target="_blank" rel="noopener">Source Music Concept ↗</a>`;
 $('maps').href='https://www.google.com/maps/dir/?api=1&origin=Gretz-Armainvilliers+77220+France&destination='+encodeURIComponent(d.place||'France')+'&travelmode=driving';
 const fmt=v=>v===null?'À compléter':money(v);
 $('costs').innerHTML=[['Artistes / intervenants',c.artists||'À renseigner'],['Véhicules',c.cars],['Prestation',fmt(c.fee)],['Route, péages et repas',fmt(c.travel)],['Total hors TVA',fmt(c.total)],['Acompte ('+state.r.deposit+' %)',fmt(c.deposit)]].map(([k,v],i)=>`<div class="cost-row ${i===4?'total':''}"><span>${k}</span><span>${v}</span></div>`).join('');
 const warnings=[];
 if(p.base==='')warnings.push('Renseigner le tarif dans Catalogue & critères.');
 if(!c.artists)warnings.push('Effectif artistique à renseigner.');
 if(d.km==='')warnings.push('Distance routière à confirmer.');
 if(p.capacity&&Number(d.participants)>Number(p.capacity))warnings.push('Capacité de cette formule dépassée : adapter le projet.');
 if(c.total!==null&&d.budget&&c.total>Number(d.budget))warnings.push('Total supérieur au budget annoncé (base HT/TTC à confirmer).');
 for(const k of ['date','place','participants'])if(!d[k])warnings.push(dLabels[k]+' à préciser.');
 if(/\bou\b|environs/i.test(d.date+' '+d.place))warnings.push('Date ou lieu alternatif : obtenir une confirmation.');
 $('warnings').textContent=warnings.join(' ');
 $('subject').value=`Proposition ${p.name}${d.company?' — '+d.company:''}${d.date?' — '+d.date:''}`;
 const price=c.total===null?'Montant : en cours de chiffrage.':`Montant de la proposition hors TVA : ${money(c.total)}\n${state.tax||'Régime fiscal et montant final à confirmer.'}\nAcompte de ${state.r.deposit} % à la réservation : ${money(c.deposit)}`;
 $('email-preview').value=`Bonjour${d.client?' '+d.client:''},\n\nMerci pour votre demande${d.context?' concernant votre événement « '+d.context+' »':''}. Je vous propose ${p.name}, une expérience adaptée à votre événement.\n\n${p.description}\n\nVotre événement\n• Date(s) envisagée(s) : ${d.date||'à définir'}\n• Lieu envisagé : ${d.place||'à définir'}\n• Participants : ${d.participants||'à préciser'}\n• Durée / horaires : ${d.duration||p.duration}\n\nNotre proposition comprend\n• ${p.name}\n• ${p.includes}\n• ${c.artists?c.artists+' artiste(s) / intervenant(s)':'Encadrement à définir'}\n${c.travel===null?'• Frais de déplacement à chiffrer':'• Frais de déplacement : '+money(c.travel)+' (inclus dans le total)'}\n\n${price}\n${p.videos?'\nDécouvrez l’animation en vidéo\n'+p.videos+'\n':''}\n${'Pour finaliser la proposition, merci de confirmer la date, l’adresse exacte, les horaires et le nombre de participants.\n\n'}Cette proposition reste soumise à confirmation des disponibilités et des modalités techniques.\n\nJe reste à votre disposition pour ajuster cette proposition à vos besoins. Pourriez-vous me confirmer la bonne réception de ce message ?\n\nBien cordialement,\nSébastien Poitevin\nMusic Concept\nsebastien@music-concept.fr\nhttps://music-concept.fr/`;
 save();
}
function renderCatalog(){
 const labels={base:'Forfait de base hors TVA (€)',perArtist:'Supplément par artiste (€)',perPerson:'Supplément par participant (€)',artists:'Effectif minimum',ratio:'Participants par intervenant (optionnel)',capacity:'Capacité maximale (optionnelle)',minCars:'Véhicules minimum',duration:'Durée proposée',keywords:'Mots-clés séparés par des virgules',includes:'Éléments inclus',description:'Présentation commerciale',videos:'Liens vidéo'};
 $('catalog-list').innerHTML=state.projects.map(p=>`<details><summary>${esc(p.name)}<small>${esc(p.category)} · ${p.base===''?'Tarif à définir':money(Number(p.base))}</small></summary><p><a href="${esc(p.source)}" target="_blank" rel="noopener">Informations du site ↗</a></p><div class="grid">${Object.entries(labels).map(([k,label])=>field(p.id+'|'+k,label,p[k],['base','perArtist','perPerson','artists','ratio','capacity','minCars'].includes(k)?'number':'text')).join('')}</div><p class="hint">Prestation = forfait + effectif × supplément artiste + participants × supplément participant. Effectif = maximum du minimum et du nombre de participants / ratio, arrondi au supérieur. Le matériel peut nécessiter des véhicules supplémentaires.</p></details>`).join('');
 $('catalog-list').querySelectorAll('input').forEach(el=>el.oninput=()=>{const[id,k]=el.dataset.field.split('|');state.projects.find(p=>p.id===id)[k]=el.value;update()});
}
function renderSettings(){const labels={seats:'Artistes par voiture (conducteur inclus)',kmRate:'Coût par km et par véhicule (€)',tolls:'Péages aller-retour par véhicule (€)',meal:'Repas par artiste (€)',deposit:'Acompte (%)'};$('settings-fields').innerHTML=Object.entries(labels).map(([k,v])=>field(k,v,state.r[k],'number')).join('');$('settings-fields').querySelectorAll('input').forEach(el=>{if(el.dataset.field==='deposit')el.max=100;if(el.dataset.field==='seats')el.min=1;el.oninput=()=>{if(!el.checkValidity()||el.value==='')return;state.r[el.dataset.field]=Number(el.value);update()}});$('tax').value=state.tax;}
function init(){$('request').value=state.request;$('project').innerHTML=state.projects.map(p=>`<option value="${esc(p.id)}">${esc(p.name)} · ${esc(p.category)}</option>`).join('');$('project').value=state.project;renderFields();renderCatalog();renderSettings();update()}
document.querySelectorAll('[data-tab]').forEach(b=>b.onclick=()=>{document.querySelectorAll('[data-tab]').forEach(x=>x.classList.toggle('active',x===b));['quote','catalog','settings'].forEach(id=>$(id).hidden=id!==b.dataset.tab)});
$('request').oninput=()=>{state.request=$('request').value;save()};
$('analyze').onclick=()=>{if(!$('request').value.trim())return;const result=analyse($('request').value,state.projects);const{ranked,...d}=result;state.d={...d,km:''};routeVersion++;$('geo-results').replaceChildren();$('route-status').textContent='Distance à calculer pour cette demande.';if(ranked.length)state.project=ranked[0].id;$('project').value=state.project;$('match-note').textContent=ranked.length?'Suggestions par mots-clés : '+ranked.slice(0,3).map(r=>state.projects.find(p=>p.id===r.id).name).join(' · '):'Aucune correspondance détectée. Choisissez une animation.';$('analysis-note').textContent='Extraction effectuée. Vérifiez les champs, notamment le contact, les dates et le lieu. Les champs vides n’ont pas été identifiés.';renderFields();update()};
$('example').onclick=()=>{state.request='Bonjour,\nContact : Naëlla\nÉvénement : séminaire d’entreprise / Team Building\nNous aimerions une animation Samba Experience pour 50 participants le 1er ou le 8 octobre 2026.\nLieu : Colombes ou ses environs\nBudget : 1000 €\nDurée : 1h15 à 1h30, horaires à définir.\nMerci pour votre proposition.';$('request').value=state.request;save()};
$('project').onchange=()=>{state.project=$('project').value;update()};$('km').oninput=()=>{if($('km').checkValidity()){state.d.km=$('km').value;routeVersion++;$('route-status').textContent='Distance saisie manuellement.';update()}};$('tax').oninput=()=>{state.tax=$('tax').value;update()};
async function fetchJSON(url){const res=await fetch(url,{signal:AbortSignal.timeout(15000)});if(!res.ok)throw Error('Service indisponible');return res.json()}
$('route').onclick=async()=>{if(!state.d.place){$('route-status').textContent='Renseignez d’abord le lieu.';return}const version=++routeVersion;$('route').disabled=true;$('route-status').textContent='Recherche du lieu…';$('geo-results').replaceChildren();try{const results=await fetchJSON('https://nominatim.openstreetmap.org/search?format=json&countrycodes=fr&limit=5&q='+encodeURIComponent(state.d.place.replace(/\s+ou\s+ses\s+environs.*/i,'')));if(version!==routeVersion)return;$('route-status').textContent=results.length?'Sélectionnez le lieu exact. Seule l’adresse est transmise aux services OpenStreetMap / OSRM.':'Lieu introuvable : précisez l’adresse ou saisissez la distance.';for(const result of results){const b=document.createElement('button');b.textContent=result.display_name;b.onclick=async()=>{const selectedVersion=++routeVersion;$('route-status').textContent='Calcul de la distance routière…';try{const origins=await fetchJSON('https://nominatim.openstreetmap.org/search?format=json&limit=1&q=Gretz-Armainvilliers%2077220%20France');if(!origins.length)throw Error();const o=origins[0];const route=await fetchJSON(`https://router.project-osrm.org/route/v1/driving/${o.lon},${o.lat};${result.lon},${result.lat}?overview=false`);if(selectedVersion!==routeVersion)return;if(!route.routes?.length)throw Error();state.d.km=String(Math.round(route.routes[0].distance/100)/10);$('km').value=state.d.km;$('route-status').textContent='Itinéraire routier estimé (OSRM) vers '+result.display_name+'. Vérifiez l’adresse finale, les péages et les accès.';$('geo-results').replaceChildren();update()}catch{if(selectedVersion===routeVersion)$('route-status').textContent='Calcul indisponible. Vérifiez sur Google Maps et saisissez les kilomètres aller.'}};$('geo-results').append(b)}}catch{if(version===routeVersion)$('route-status').textContent='Service indisponible. Utilisez Google Maps puis saisissez la distance aller.'}finally{$('route').disabled=false}};
const fullMail=()=>`Objet : ${$('subject').value}\n\n${$('email-preview').value}`;
$('copy').onclick=async()=>{try{await navigator.clipboard.writeText(fullMail());$('copy-status').textContent='Mail copié.'}catch{$('email-preview').select();$('copy-status').textContent='Sélectionnez le texte puis copiez-le avec Ctrl/Cmd+C.'}};
function download(name,text,type){const url=URL.createObjectURL(new Blob([text],{type}));const a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}
$('download').onclick=()=>download('proposition-music-concept.txt',fullMail(),'text/plain;charset=utf-8');$('backup').onclick=()=>download('music-concept-sauvegarde.json',JSON.stringify(state,null,2),'application/json');
$('restore').onchange=async e=>{try{const s=JSON.parse(await e.target.files[0].text());if(!Array.isArray(s.projects)||s.projects.length!==13||!s.d||!s.r||typeof s.request!=='string'||typeof s.tax!=='string')throw Error();for(const key of Object.keys(defaults.d))if(typeof s.d[key]!=='string')throw Error();for(const key of Object.keys(defaults.r))if(!Number.isFinite(Number(s.r[key]))||Number(s.r[key])<0)throw Error();if(s.r.seats<1||s.r.deposit>100)throw Error();s.projects.forEach((p,i)=>{if(p.id!==String(i))throw Error();for(const k of Object.keys(initialCatalog[i]))if(typeof p[k]!=='string'&&typeof p[k]!=='number')throw Error();for(const k of ['base','perArtist','perPerson','artists','ratio','capacity','minCars'])if(!Number.isFinite(Number(p[k]))||Number(p[k])<0)throw Error();p.source=initialCatalog[i].source});state=s;routeVersion++;init();$('restore-status').textContent='Sauvegarde importée.'}catch{$('restore-status').textContent='Fichier invalide : aucune donnée importée.'}};
$('print').onclick=()=>{const pre=document.createElement('div');pre.className='print-mail';pre.textContent=fullMail();document.querySelector('.preview').append(pre);window.print();pre.remove()};init();
